SITE_TITLE: "Seam Project"
VIEWS_PATH: src/views
PUBLIC_PATH: public
FORCE_WWW: true
PORT: 3031
GOFUNDME_URL: https://www.gofundme.com/seam-project
FACEBOOK_URL: https://www.facebook.com/events/249938589032183/
GOOGLE_ANALYTICS_ACCOUNT_ID: UA-124258828-1
